project:
  type: website
  output-dir: docs
  resources:
    - maps/widgets/**

website:
  title: "REPBIAS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: origins.qmd
        text: Origins of Institutions
      - href: malapportionment-bias.qmd
        text: Malapportionment Bias
      - href: minority-representation.qmd
        text: Minority Representation
      - href: decomposing-bias.qmd
        text: Decomposing Bias
      - href: papers.qmd
        text: Papers
      - href: team.qmd
        text: Team

lang: en

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true

editor: visual
